{% set data = load_setup_py_data() %}

package:
  name: "pymt_prms_surface"
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - cython
    - numpy 1.11.*
    - model_metadata
    - bmi-fortran=2.0 
    - prms 
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - bmi-fortran=2.0 
    - prms 

test:
  requires:
    - bmi-tester
    - model_metadata
  imports:
    - pymt_prms_surface
  commands:
    - config_file=$(mmd-stage PRMSSurface . > MANIFEST && mmd-query PRMSSurface --var=run.config_file.path)
    - bmi-test pymt_prms_surface.bmi:PRMSSurface --config-file=$config_file --manifest=MANIFEST -v

about:
  summary: Python package that wraps the prms_surface BMI.
  home: https://github.com/csdms/pymt_prms_surface
  license: MIT license
  license_file: LICENSE
  dev_url: https://github.com/csdms/pymt_prms_surface
